jobs:
  pypi-publish:
    name: upload release to TestPyPI
    runs-on: ubuntu-latest
    environment: testpypi  # optional but recommended
    permissions:
      id-token: write  # required for Trusted Publishing
    steps:
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-testpypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
